-- MySQL Script generated by MySQL Workbench
-- Thu Aug 23 19:01:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ContactBook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ContactBook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ContactBook` DEFAULT CHARACTER SET utf8 ;
USE `ContactBook` ;

-- -----------------------------------------------------
-- Table `ContactBook`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ContactBook`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `ContactBook`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ContactBook`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `userid` INT NOT NULL,
  PRIMARY KEY (`userid`));


-- -----------------------------------------------------
-- Table `ContactBook`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ContactBook`.`contacts` (
  `contact_first_name` VARCHAR(45) NULL,
  `contact_last_name` VARCHAR(45) NULL,
  `contact_email` VARCHAR(45) NULL,
  `contact_phone` VARCHAR(45) NULL,
  `contact_id` INT NULL,
  INDEX `userid_idx` (`contact_id` ASC),
  CONSTRAINT `userid`
    FOREIGN KEY (`contact_id`)
    REFERENCES `ContactBook`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'root' IDENTIFIED BY 'password';

GRANT ALL ON `ContactBook`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
