-- MySQL Script generated by MySQL Workbench
-- Fri Aug 31 14:15:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ContactBook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ContactBook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ContactBook` DEFAULT CHARACTER SET utf8 ;
USE `ContactBook` ;

-- -----------------------------------------------------
-- Table `ContactBook`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ContactBook`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `userid` INT NOT NULL,
  PRIMARY KEY (`userid`));


-- -----------------------------------------------------
-- Table `ContactBook`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ContactBook`.`contacts` (
  `contact_first_name` VARCHAR(45) NULL,
  `contact_last_name` VARCHAR(45) NULL,
  `contact_email` VARCHAR(45) NULL,
  `contact_phone` VARCHAR(45) NULL,
  `contact_userId` INT NULL,
  `contactId` VARCHAR(45) NOT NULL,
  `contact_address1` VARCHAR(45) NULL,
  `contact_address2` VARCHAR(45) NULL,
  `contact_city` VARCHAR(45) NULL,
  `contact_state` VARCHAR(45) NULL,
  `contact_zipcode` INT NULL,
  PRIMARY KEY (`contactId`))
ENGINE = InnoDB;

CREATE USER 'root' IDENTIFIED BY 'password';

GRANT ALL ON `ContactBook`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
